server:
  port: 8082

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5000KB
      max-request-size: 5000KB
      resolve-lazily: true
  datasource:
    url: jdbc:postgresql://localhost:5439/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: depixen-pass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update


firebase:
  bucket-name: ...